### ISSUE TITLE
【ヒール＆軽減】戦士（シェイクオフ）が表示されない

### ISSUE THREAD

**Issue by kkk30** [okapiffxiv/xivtlsheet#5]
オメガ零式４層ACTログから作成。
また、最後の方になると数字のみが表示されたままになる。
（背景が変化せず数字のみが残ったまま）

**Comment by okapiffxiv** [comment]
手元のデータで状況を再現できないので、
よろしければログを貼り付けたテキストファイルを以下のGoogleドライブにアップロードお願いします
https://drive.google.com/drive/folders/1EU01m-wVR1br_LNJoRf_mLbXnJxEPIkD?usp=sharing

**Comment by kkk30** [comment]
アップロードしておきました。

**Comment by okapiffxiv** [comment]
確認してみましたが、やはり自分の環境では再現できないですね‥
少し修正してみたので試しに最新のブックで試していただいてもよろしいですか？
[リンク](https://github.com/okapiffxiv/xivtlsheet#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97)

基本上のセル書式をコピーしているはずなのでセルの中身が『1』『2』『0』なら色が付くよう設定される筈なのですが、
もしならなかったら、レイアウトが反映されていない状況を確認したいのでブックをそのままGoogleドライブにコピーしていただけると助かります

**Comment by kkk30** [comment]
今週末辺りに置きますので少々おまちください

**Comment by kkk30** [comment]
ブラウザ依存かと思い一応Chromeでも実施してみました。
EdgeとChromeで実施した結果を閲覧用としてリンク張っておきました。
（ドライブの方においてあります）
Chromeの方はそもそも何も表示されません。

**Comment by okapiffxiv** [comment]
ありがとうございます。以下、内容確認お願いします。
> Edge

メニューより「タイムライン ＞ ユーザ設定」より対象のユーザ名を設定してください  
そのユーザがシェイクオフを受けたときのタイミングを出力しています

> Chrome

logsシートの１－１０行目までが空欄になっているので上に詰めて入力をお願いします

よろしくおねがいします

**Comment by kkk30** [comment]
遅くなってすみません。
年末でバタバタしたもので明日か明後日には確認させてもらいます。

**Comment by kkk30** [comment]
ユーザー名を設定すると確かに出力はしました。ありがとうございます。
ただ少し不便かな、と感じました。
全体バリア系はシェイクオフ（被）のような感じでPTメンバー全員のがわかるようになっていると
見るとき嬉しいです。
この人はここでバリア分軽減されているな、と一目でわかるといいかな、と。

**Comment by okapiffxiv** [comment]
表示されたようで良かったです。
全体バフ系についてですが、たしかに初めはそのように作ってたのですが、

- 範囲外にいてバフもらっていない人がいた場合、死んだ原因が探りづらい時がある
- シェイクオフが一人だけ早く切れるパターンがあり(単体攻撃やAA)、バフが切れるタイミングを判断しづらい

という事があり、対処として『ユーザ名を設定』を組み込んだ、という流れです。
> 全体バリア系はシェイクオフ（被）のような感じでPTメンバー全員のがわかるようになっていると

これ良さそうですね
横が長くなりすぎないかなーと思ったのですが、今でもヒール系のシートは長いし…
ちょっと試してみますｂ
