### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by kkk30** [okapiffxiv/xivtlsheet#7]
FFlogsのものも読み込めるような作りになっていると思いますが、
この場合どうやって取り込むのでしょうか？
すみませんがやり方がいまいちわからなかったので教えていただけると助かります。

**Comment by okapiffxiv** [comment]
[README](https://github.com/okapiffxiv/xivtlsheet/blob/master/README.md#fflogs%E3%81%AE%E5%A0%B4%E5%90%88)にFFlogsからの読み込み方法を追加しました。
よろしくおねがいします。

**Comment by kkk30** [comment]
ありがとうございます。
しかし、FFlogsー＞タイムライン作成を実行すると以下のようになります。
新たにスプレッドシートにコピーして再試行しても同様でした。

![default](https://user-images.githubusercontent.com/20177503/50534079-531f8100-0b7a-11e9-8f8e-67698983f84f.PNG)

**Comment by okapiffxiv** [comment]
ソースに書き漏れがありました
修正しましたので、お手数ですが再度 [こちら](https://github.com/okapiffxiv/xivtlsheet#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97) から取り込みをお願いします

**Comment by kkk30** [comment]
ご対応ありがとうございます。
正常に取り込めました。
