### ISSUE TITLE
質問２

### ISSUE THREAD

**Issue by kkk30** [okapiffxiv/xivtlsheet#9]
絶アルテマのFFlogsにて確認していたのですが、
赤のアドル、アポカタが軽減で表示されないようにみえます。
FFlogsキャストの画像を見るとちゃんとこの方は４回アドルをうっていると思います。
ただタイムラインシートでは何も表示されません。
参考に別ユーザーの召喚で確認したところ、召喚ではちゃんと表示されていました。

特定のジョブはまだ未対応ということでしょうか？
であるならば、どれが正式に対応済みか教えてもらえると助かります。

【タイムラインシート】
![default](https://user-images.githubusercontent.com/20177503/50535105-93d2c680-0b89-11e9-93a0-8d97fc9b1a06.PNG)

【FFlogsキャスト】
![fflogs](https://user-images.githubusercontent.com/20177503/50535108-a64d0000-0b89-11e9-80fd-f30a1d749e3a.PNG)

【参考：召喚】
![default](https://user-images.githubusercontent.com/20177503/50535130-fdeb6b80-0b89-11e9-90ed-7e23d215ffa4.PNG)

**Comment by okapiffxiv** [comment]
> 赤のアドル、アポカタが軽減で表示されないようにみえます。

こちら修正しました。

> どれが正式に対応済みか教えてもらえると助かります。

『戦ナ占学竜忍詩召』で固定活動を行っているので、それ以外位のジョブは検証不足なところがあります。
ですが、スプレットシートに表示している箇所に関しましてはサポートしますのでまた不具合箇所ありましたら気軽に連絡いただけると助かります。
